### PR TITLE
Update config.yml

### LINKED ISSUE #353: Modellbildung und Simulation Main Page dead!
#351 killed the main page. Both Philipp and me forgot to check the demo site before merging because it was such a small change.

### PR DESCRIPTION
**Pull request by joergbrech**
do link check in seperate step. 

Fixes #353 

# Description

## Checklist

 - [x] This pull request is associated to an issue
 - [x] All used resources use a CC-by-SA license or less and are marked appropriately, see our [contribution guide](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/CONTRIBUTING.md).
 - [x] All used resources have been added to [list_of_all_resources.md](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/docs/List_of_all_resources.md)
 - [x] New exercises include learning requirements and learning goals.
 - [x] Add @LeaKruehler as reviewer and wait for approval just before merging.

### CODE REVIEW

**Comment by PhiSpel** [comment]
I will prioritise this over #354 , hopefully it works :)

**Comment by joergbrech** [comment]
Ah sorry, apparently we simultaneously opened a PR. BTW, I am not 100% sure if this works. It seemed to me that the link check option *only* checks the links without actually building the site.

**Comment by joergbrech** [comment]
Seems to work!

**Comment by PhiSpel** [comment]
The artifacts look good. I will try in a separate pr to replicate the error and see what the artifacts looked like

**Comment by joergbrech** [comment]
> Edit: nvm, the html were not build, only the image files..

Exactly, we have the redirect htmls and the manually copied images, but not the htmls generated by jb from the markdown and jupyter notebook files. So I am really guessing that the link checker option **only** checks the links without generating any output.

**Pull request merged**
