### PR TITLE
Update test_groundwater_sim.m

### PR DESCRIPTION
**Pull request by m-r-schenk**
Changed the limits of the expected wetted cells. Now we really expect ground(1,20:60) to be wet. Was ground(1,19:61) before...

### CODE REVIEW

**Comment by PhiSpel** [comment]
I remember we did this exercise and although it explicitly says "Die Ränder der Bodenmatrix sind gesondert zu behandeln." I think there was some reasoning behind this. Maybe @joergbrech can help out?

**Comment by joergbrech** [comment]
Hi guys, I don't remember the details, but  I added the Musterlösung here: https://github.com/hbrs-cse/modsim-Musterloesungen/blob/main/00_einleitung/04_exercises/groundwater_sim.m (private repo).

**Comment by PhiSpel** [comment]
Thank you, @joergbrech ! I tried running the moxunit test on it, but `test_groundwater_sim.m` cannot be found..

`error: Parameter not recognised or file missing: test_groundwater_sim.m
error: called from
    moxunit_runtests>get_params at line 329 column 21
    moxunit_runtests at line 72 column 11`

@m-r-schenk did you run into the same issue?

**Comment by joergbrech** [comment]
Did you try it locally or online? Online we have the problem because of this regression: https://github.com/joergbrech/Modellbildung-und-Simulation/issues/112. binder starts in the root directory of this repo so you will have to specify the full path to the subdirectory where `test_groundwater_sim.m` lies.

**Pull request merged**
