### PR TITLE
moved matlab introduction to a separate section

### LINKED ISSUE #169: Übungen aus der Einleitungen präsenter machen
Es gibt eine schöne Sammlung von Übungen in der Einleitung: https://joergbrech.github.io/Modellbildung-und-Simulation/00_einleitung/04_exercises/00_%C3%BCbungsaufgaben.html, die allerdings etwas versteckt sind. Ich plädiere dafür, dass wir sie prominenter in einem eigenen Kapitel präsentieren.

### LINKED ISSUE #272: Move Schwingungen chapter?
after ODEs / beginning of ModSim2

### PR DESCRIPTION
**Pull request by PhiSpel**
- ...and added first two exercises from Patrick
- How do you like this layout? I tried to stick close to your solutions.
- I added code boxes where students should be able to create their own code online
- An example solution is already shown in the videos, so I added expandable code-boxes. Or should I leave them out to not give out too easy solutions for students?
- Where did you get the images? Under which licences?
- The links to the files do not work for me, as the build function does not include them. I'm on it...

- [x] add an overview over the video/data MATLAB introduction course
- [ ] box the admonition in the overview chapter
- [x] move Schwingungen behind ODEs

We will not do (Robin, Gerd and I agree):
- reference topics in other chapters
- "Zusatzbeispiel" + <Title> in each chapter
- requirements: previous chapter
- in the end of exercise: reference to next chapter

associated to #181 (check file download before closing the issue)
Closes #169 
closes #272

### CODE REVIEW

**Comment by PhiSpel** [comment]
"Grundlagenkurs und Zusatzübungen"

**Comment by PhiSpel** [comment]
There needs to be an overall thread to the whole book - how can we still integrate the matlab Grundlagenkurs exercises into the book, instead of "a book in a book"?

- [ ] "Zusatzbeispiel" + <Title> in each chapter
- [ ] requirements: previous chapter
- [ ] in the end of exercise: reference to next chapter

**Review by m-r-schenk — APPROVED** [review]
I technically reviewed this work. Merging the substantially diverged master into this was a pain. But this should be functional now. Please @PhiSpel review if everything is as intended now. And maybe present this in the meeting.

I think we can merge this into master now and maybe start a new issue after discussion in the group.

**Comment by PhiSpel** [comment]
> I technically reviewed this work. Merging the substantially diverged master into this was a pain. But this should be functional now. Please @PhiSpel review if everything is as intended now. And maybe present this in the meeting.

Will do

> I think we can merge this into master now and maybe start a new issue after discussion in the group.

I agree! The exercises can be published, the improvements can be done in a separate issue

**Comment by PhiSpel** [comment]
@joergbrech github says content/_toc.yml is a conflicting file, although it is marked in .gitignore
How can we fix this?

With your approval / re-review / dismissed review we can merge. This should be done before April so we have the chapter order for the lecture

**Comment by joergbrech** [comment]
I merged master into this branch and then deleted the `_toc.yml`. We still don't need it right? I say let's merge if the checks are successful and the demo site seems ok. We can always open a new issue if we notice something.

**Review by joergbrech — APPROVED** [review]
I haven't actually checked the whole thing, but let's favor speed over a full review on this one. @PhiSpel @m-r-schenk: If you agree, let's merge!

**Comment by PhiSpel** [comment]
Further improvements can be solved in separate issues/PRs

**Pull request merged**
