### PR TITLE
added animations for example solutions with velocity c(t)

### LINKED ISSUE #187: Add Zusatzaufgabe for convection-diffusion exercise
- [ ] I would like to extend the example by adding a pulsing flow velocity c(t). Currently this is just a short sentence in "Zusatzaufgabe". We could open a new issue so that we don't forget to add more concrete directions and also an animation.

### PR DESCRIPTION
**Pull request by PhiSpel**
this should give a good idea of what to do in the Zusatzaufgabe

closes #187

### CODE REVIEW

**Review by joergbrech — CHANGES_REQUESTED** [review]
Wow, that was quick :)

 - Can we have the different plots in one plot? This way we can see the difference between constant c and time dependent c better.
 - Can we use parameters that are a good compromise between "we can see the influence of the parameters in our plots" and "physically plausible"? Your first two exampes imply a pulse of 120, in your third example the blood flow stops and in the fourth the bloodflow increases exponentially. sines and cosines are fine for demonstration purposes. Here is something remotely realistic: https://images.app.goo.gl/otZkPUULFfpyb6pd8. We could mention the simplifications explicitly as part of the exercise

**Comment by PhiSpel** [comment]
> Wow, that was quick :)
> 
> * Can we have the different plots in one plot? This way we can see the difference between constant c and time dependent c better.

Done :)

> * Can we use parameters that are a good compromise between "we can see the influence of the parameters in our plots" and "physically plausible"? Your first two exampes imply a pulse of 120, in your third example the blood flow stops and in the fourth the bloodflow increases exponentially. sines and cosines are fine for demonstration purposes. Here is something remotely realistic: https://images.app.goo.gl/otZkPUULFfpyb6pd8. We could mention the simplifications explicitly as part of the exercise

I added comments about this under the figures. In the article you drew the graph from, I could not find the base-frequencies they used. Do you have a source for this?

**Comment by joergbrech** [comment]
> I could not find the base-frequencies they used. Do you have a source for this?

To be honest, this was just a quick 20 second google search, so no.


I think we should use a very basic estimate of realistic parameters. For this, I suggest

 - to check again the parameters of "Aufgabe 2". In hindsight, we should've chosen somewhat realistic parameters here as well. Also, units are missing.
    - mean blood velocity c: https://images.app.goo.gl/YmvRWgDAo9mREcix6
    - diffusion coefficient: Very hard to guess, we could look at diffusion coefficients in water: https://de.wikipedia.org/wiki/Diffusionskoeffizient
 - to remove the exponential velocity examples. Physically, they don't make sense and are a bit scary ;)
 - to rethink the cosine and sine pulse: I know, I said using them as an approximation is okay, but I just realized that they both have a zero mean blood velocity, which is also scary. We should use a periodic function with a frequency of the human pulse and a realistic mean velocity. A heart rate of 120 is quite high for an adult.
 - to add a short paragraph on how these parameters where chosen and that they are not super-realistic, just "physically motivated" to get a feel for the problem.

Then for the animations I also have two suggestions:
 - Can we add a legend? The animations jump right into the eye, and a reader takes some time to parse the text for the information what the animations show.
 - I would stop the animation before the right tail of the insect poison reaches the right limit: We chose constant boundary conditions and they are a terribly wrong boundary if the blood is transported close to the right edge. As a consequence, the results cannot be trusted anymore at all.

**Comment by PhiSpel** [comment]
> > I could not find the base-frequencies they used. Do you have a source for this?
> 
> To be honest, this was just a quick 20 second google search, so no.
> 
> I think we should use a very basic estimate of realistic parameters. For this, I suggest
> 
> * to check again the parameters of "Aufgabe 2". In hindsight, we should've chosen somewhat realistic parameters here as well. Also, units are missing.
>   
>   * mean blood velocity c: https://images.app.goo.gl/YmvRWgDAo9mREcix6

Done. I added SI units in the example and an admonition about this below the figure.

>   * diffusion coefficient: Very hard to guess, we could look at diffusion coefficients in water: https://de.wikipedia.org/wiki/Diffusionskoeffizient

This seems rather arbitrary. E.g., the diffusion coefficient for CO2 is 20 times higher than for O2 (I did not find specific values), see [here](https://flexikon.doccheck.com/de/Gasaustausch#:~:text=Der%20Diffusionskoeffizient%20liegt%20f%C3%BCr%20CO,die%20Membran%20als%20O2.). I think it is better to stick to an admonition without specifying a realistic diffusion coefficient.

> * to remove the exponential velocity examples. Physically, they don't make sense and are a bit scary ;)

Done

> * to rethink the cosine and sine pulse: I know, I said using them as an approximation is okay, but I just realized that they both have a zero mean blood velocity, which is also scary. We should use a periodic function with a frequency of the human pulse and a realistic mean velocity. A heart rate of 120 is quite high for an adult.

Done, I used the mean velocity plus a sine function and added the admonition according to your source.

> * to add a short paragraph on how these parameters where chosen and that they are not super-realistic, just "physically motivated" to get a feel for the problem.

Done

> 
> Then for the animations I also have two suggestions:
> 
> * Can we add a legend? The animations jump right into the eye, and a reader takes some time to parse the text for the information what the animations show.

I added a legend and, to slim the page, left it with only one animated image in Zusatzaufgabe and a reference in Aufgabe 2.

> * I would stop the animation before the right tail of the insect poison reaches the right limit: We chose constant boundary conditions and they are a terribly wrong boundary if the blood is transported close to the right edge. As a consequence, the results cannot be trusted anymore at all.

Done

**Comment by joergbrech** [comment]
Very nice!

Going over the exercise 2 again, I realized, that we should probably also provide some more explicit instructions for numerical experminets regarding the comparison of the explicit Euler and the Crank-Nicolson regimes. In you rplots its hard to see a difference, I assume because the step size is chosen small enough. But this is definitely something for a new issue. Let's merge!

**Review by joergbrech — APPROVED** [review]

**Pull request merged**
