### PR TITLE
Update sync.yml

### PR DESCRIPTION
**Pull request by PhiSpel**
# Description

The test run worked, see [this result](https://github.com/PhiSpel/Modellbildung-und-Simulation-1/actions/runs/3830613534/jobs/6518710712), with `test_mode: true`

https://github.com/PhiSpel/Modellbildung-und-Simulation-1/blob/d402e8a004620fbafa659966953da4da7086abd2/.github/workflows/sync.yml#L24.

I suggest we just force update the branch.

### CODE REVIEW

**Review by joergbrech — APPROVED** [review]
nice! thanks

**Comment by PhiSpel** [comment]
Apparently, this did not do the trick..

**Comment by joergbrech** [comment]
💩

**Comment by PhiSpel** [comment]
I used a different action, which seems to work, see #2

**Pull request merged**
