### PR TITLE
bump to jb 0.10.0

### PR DESCRIPTION
**Pull request by sandro-elsweijer**

### CODE REVIEW

**Comment by joergbrech** [comment]
@sandro-elsweijer I think something changed in the myst parser, causing the error. I think its related to this line:

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/4e60c7301f25c47cf15cfac50b009365dd409745/content/_config.yml#L63-L64

We could try to just copy this part of the config from the jb demo? That's what I did before:

https://github.com/executablebooks/jupyter-book/blob/696b7175e580faaa249edd93d1119d07343e680d/docs/_config.yml#L38-L51

**Comment by joergbrech** [comment]
Also, could you delete this line?

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/4e60c7301f25c47cf15cfac50b009365dd409745/requirements.txt#L2

See our discussion in the issue description.

**Comment by sandro-elsweijer** [comment]
I was able to correct the error generated by the bump in the jb version, but now something seems to be wrong with Sphinx. It does not recognize the `cite` and `bibliography` commands anymore. When I build the book with `jupyter-book build -W -n --keep-going .`, which is proposed [here](https://jupyterbook.org/content/citations.html), the errors vanish. It works even if I build the book with `jupyter-book build -W .` after that. It seems to me, that the `-n` option "reminds" Sphinx how to handle citations, but I am not able to find another way to handle this.

**Comment by joergbrech** [comment]
In the link to the jupyter-book reference, it says

> List your bibtex file in your configuration. In order to activate citations, list your references file like so:
> 
> # In _config.yml
> bibtex_bibfiles:
>    - references.bib
> 
> This will activate the sphinxcontrib.bibtex extension

So I suppose we should explicitly reference all bib files in our config file to get it to work?

**Review by joergbrech — APPROVED** [review]

**Pull request merged**
