### PR TITLE
bump jupyter book to v0.11.3

### LINKED ISSUE #174: Bump jupyter-book to 0.11.3

### PR DESCRIPTION
**Pull request by sandro-elsweijer**
# Description

closes #174

## Checklist

 - [x] This Pull request is associated to an issue
 - [x] All used resources use a CC-by-SA license or less and are marked appropriately, see [our contribution guide](CONTRIBUTING.md).
 - [x] All used resources have been added to the list in `[TODO, does not exist yet]`
 - [x] New exercises include learning requirements and learning goals.

### CODE REVIEW

**Comment by sandro-elsweijer** [comment]
@joergbrech @PhiSpel 
The new toc command and also the build command are quite long. A script for building the book might be useful, but it is also possible to write aliases in our `.bashrc`. But we have to keep these updated by ourselves. What do you think works best?

**Comment by joergbrech** [comment]
Nice! It seems like the commenting feature will work after this. Everyone, remember to update your local jupyter-book version!

**Comment by joergbrech** [comment]
> A script for building the book might be useful, but it is also possible to write aliases in our .bashrc. But we have to keep these updated by ourselves. What do you think works best? 

I think it's fine as long as you can just copy and paste it from the contribution guide. Also, it is not strictly required for contributing content, because the command is executed as part of our CI, it is only needed if you want to build the pages locally on your computer. Therefore I say everyone is responsible if they want to define an alias, use a script or just copy and paste the command each time. This saves us the hastle of having to maintain the script for differenct platforms *(bash/cmd or powershell)*

**Comment by sandro-elsweijer** [comment]
Oh, I totally forgot that people also could use something else than bash, it seems so absurd 😁

**Pull request merged**
