### PR TITLE
Inserted special content boxes

### LINKED ISSUE #93: Show hints as {admonition}
In some chapters there are hints on how to approach a task or what to google to find the solution. Using MyST, I would propose to use the [{admonition} directive](https://jupyterbook.org/content/content-blocks.html#notes-and-warnings) for hints instead of printing it **bold**

### LINKED ISSUE #99: Update jb to 0.8.x
jupyter-book introduced named admonition boxes in 0.8.0, so we should update our jupyter book version accordingly. This issue is related to #93

### PR DESCRIPTION
**Pull request by sandro-elsweijer**
I nested all `Hinweise` into a [special content box](https://jupyterbook.org/content/content-blocks.html#notes-and-warnings).
Jupyter Book implemented a [Markdown friendly style for admonitions](https://jupyterbook.org/content/content-blocks.html#new-style-admonitions) in [0.8.0](https://jupyterbook.org/reference/_changelog.html#new-and-improved), so I switched to 0.8.3.

Fixes #93 
Fixes #99

### CODE REVIEW

**Comment by sandro-elsweijer** [comment]
It wasn't me: https://github.com/executablebooks/jupyter-book/issues/1137#issuecomment-743993738

**Comment by sandro-elsweijer** [comment]
sphinx-bibtex just released an incompatible version, that is why I added `sphinxcontrib-bibtex==1.0.0` to `requirements.txt`

**Comment by joergbrech** [comment]
@sandro-elsweijer thanks! The commit history looks like this was a frustrating one :wink: 

I have two minor problems with this PR:
 - I would have preferred two different sets of issue-branch-PR triplets: One for an update to a new jupyter-book version, and another one for the admonitions. That would have given us a cleaner history. That way it would have been less likely that someone misses the jb update: With every bump of the jb version for this book, everybody working on this book must manually install the newer version. 
 - I am not superhappy with having to maintain the jupyter book dependencies in our requirements.txt. This should be handled on the jupyter book side.

That said, those issues really are minor and I am fine with a merge. I will open a new issue to remind ourselfs to remove the `sphinxcontrib-bibtex` dependency when we do the next jb version bump to 0.8.4.

**Comment by joergbrech** [comment]
Fixes #93 
Fixes #99

**Review by joergbrech — APPROVED** [review]

**Comment by sandro-elsweijer** [comment]
@joergbrech I will remember this for the next time, thanks.

**Pull request merged**
